FROM alpine

CMD ["echo", ""]
CMD ["echo", "----------------------------------------"]
CMD ["echo", ""]
CMD ["echo", "hello world"]
CMD ["echo", ""]
CMD ["echo", "----------------------------------------"]


