version: '3'

services:
   ubuntu:
      container_name: demo
      image: ubuntu:latest
      ports: - 80:80
#      command: bash -c "apt-get update;apt-get install -y git;apt-get install -y npm;apt-get install -y curl;apt-get install -y vim;npm i -g npx"
