version: '3'

services:
   ubuntu:
      container_name: demo
      image: ubuntu:latest
      command: bash -c "apt update; apt -y install curl;apt -y install git;curl -fsSL get.docker.com -o get-docker.sh;sh get-docker.sh;curl --version;git --version;docker --version"
